services:
  route_reader_integration_test_zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 12183:2181   
  
  route_reader_integration_test_kafka_server:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - route_reader_integration_test_zookeeper
    ports:
      - 9095:9095
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: route_reader_integration_test_zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://route_reader_integration_test_kafka_server:9093,PLAINTEXT_HOST://localhost:9095
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1    
 